### PR TITLE
Refactor, clear, make compile

### PR DESCRIPTION
**Pull request by alehatsman**

### CODE REVIEW

**Review by julienba — COMMENTED** [review]
First, thanks for contributing ! Nice works.

I have 3 tests failing ( see below for an example ), all related to dates. Did you get the same errors ?


```
failure in (date_bucketing_test.clj:221) : metabase.query-processor-test.date-bucketing-test
(expect (metabase.test.data.datasets/do-with-engine :athena expected--1322167448) (metabase.test.data.datasets/do-with-engine :athena actual--1961
778000))

           
expected:
 [["2015-06-01T03:31:00.000-07:00" 1]
 ["2015-06-01T09:06:00.000-07:00" 1]
 ["2015-06-01T10:23:00.000-07:00" 1]
 ["2015-06-01T11:55:00.000-07:00" 1]
 ["2015-06-01T14:04:00.000-07:00" 1]
 ["2015-06-01T14:19:00.000-07:00" 1]
 ["2015-06-01T19:13:00.000-07:00" 1]
 ["2015-06-01T22:37:00.000-07:00" 1]
 ["2015-06-02T01:20:00.000-07:00" 1]
 ["2015-06-02T04:11:00.000-07:00" 1]]
 
was:
 [["2015-06-01T10:31:00.000-07:00" 1]
 ["2015-06-01T16:06:00.000-07:00" 1]
 ["2015-06-01T17:23:00.000-07:00" 1]
 ["2015-06-01T18:55:00.000-07:00" 1]
 ["2015-06-01T21:04:00.000-07:00" 1]
 ["2015-06-01T21:19:00.000-07:00" 1]
 ["2015-06-02T02:13:00.000-07:00" 1]
 ["2015-06-02T05:37:00.000-07:00" 1]
 ["2015-06-02T08:20:00.000-07:00" 1]
 ["2015-06-02T11:11:00.000-07:00" 1]]
```

**Comment by alehatsman** [comment]
@julienba, please merge master brach to your branch, so that there will be more clear commit history. 

I will check about date tests. I remember something similar, i will check.

**Comment by alehatsman** [comment]
Yes i see those errors and a lot of others, any ideas on what is going on ?

**Comment by julienba** [comment]
It has been merged with master

**Comment by alehatsman** [comment]
ok, i updated my brach to make everything clear

**Review by julienba — APPROVED** [review]

**Comment by julienba** [comment]
:+1:

**Pull request merged**
